### ISSUE TITLE
成就1a重置不掉

### ISSUE THREAD

**Issue by Final0i00000000a7** [dlsdl/wind_spirit_creation#3]
众所周知，gte的意思不是判断大于等于某个数值，也不是
***G***reater***T***henOr***E***qualTo
而是判断大于某个数值
# 这恒河理
<picture>
  <img alt="bugfound" src="https://github.com/dlsdl/wind_spirit_creation/assets/140218829/674fcae0-9a2a-4cfb-92dd-bd9be6247e1a" />
</picture>

**Comment by VeryrrDefine** [comment]
这哪里河理了
